### ISSUE TITLE
作者你好，请问会开放项目的数据吗?

### ISSUE THREAD

**Issue by HuarongLi** [ownthink/KnowledgeGraph#3]
做的比较全，后面数据会开放出来么？但是歧义词处理好像不太好，比如苹果是表示植物的苹果还是apple公司

**Comment by ownthink** [comment]
@HuarongLi ，数据集已经开放了，可以免费申请。歧义关系已经有的，你可以用歧义关系（mention -> entity）api请求到歧义关系，例如：苹果
https://api.ownthink.com/kg/ambiguous?mention=苹果
苹果可以表示植物的苹果，苹果[蔷薇科苹果属果树]、苹果[蔷薇科苹果属果实]，或者是苹果公司等，然后再利用歧义关系api请求到的歧义实体获取实体知识，实体知识可以利用实体知识（entity -> knowledge）api获取。
例如：苹果[蔷薇科苹果属果树]，苹果公司
https://api.ownthink.com/kg/knowledge?entity=苹果[蔷薇科苹果属果树]
https://api.ownthink.com/kg/knowledge?entity=苹果公司

**Comment by HuarongLi** [comment]
好的，非常感谢，数据集可以在哪里申请呢？

**Comment by ownthink** [comment]
@HuarongLi 将自己的信息发送到help@ownthink.com，说明申请获取知识图谱数据。

**Comment by HuarongLi** [comment]
好的，非常感谢！
